# Generated by Django 5.0 on 2023-12-22 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('document_proof', models.CharField(blank=True, choices=[('AADHAR', 'Aadhar card'), ('VOTER', 'Voter id')], max_length=10, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=255, null=True)),
                ('voter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_image', models.ImageField(blank=True, null=True, upload_to='tenant_image')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
