# Generated by Django 5.0 on 2023-12-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rent_cost', models.PositiveIntegerField(default=0)),
                ('unit_type', models.CharField(blank=True, choices=[('1BHK', '1 Bedroom Hall Kitchen'), ('2BHK', '2 Bedroom Hall Kitchen'), ('3BHK', '4 Bedroom Hall Kitchen'), ('4BHK', '1 Bedroom Hall Kitchen')], max_length=10, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
