# Generated by Django 5.0 on 2023-12-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_unit_property_alter_unit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_avail',
            field=models.BooleanField(default=True),
        ),
    ]
