# Generated by Django 5.0 on 2023-12-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_unit_is_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
